// 타겟 경로: src/app/preview/page.tsx
"use client";

import React, { useState, useRef, useEffect, FormEvent } from 'react';
import { Sidebar } from '@/components/Sidebar';
import apiClient from '@/api/index';
import { useTranslation } from '@/hooks/useTranslation';

interface ChatMessage {
  id: string;
  sender: 'ai' | 'user';
  text: string;
}

export default function PreviewScreen() {
  const shopId = '3sesac18';
  const postId = '';

  const { t } = useTranslation();

  const [messages, setMessages] = useState<ChatMessage[]>([
    { id: '1', sender: 'ai', text: t.preview.greeting },
  ]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // 🚨 [추가] 우측 텍스트 에디터 참조 및 화면 분할 비율(33.3% ~ 66.6%) 상태 관리
  const rightTextareaRef = useRef<HTMLTextAreaElement>(null);
  const [textRatio, setTextRatio] = useState(50); // 기본 절반(50%)

  const [allPhotos, setAllPhotos] = useState<any[]>([]);
  const [images, setImages] = useState<any[]>([]);
  const [tempSelectedPhotos, setTempSelectedPhotos] = useState<any[]>([]);

  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [isEditModalVisible, setIsEditModalVisible] = useState(false);
  const [isOrderModalVisible, setIsOrderModalVisible] = useState(false);

  const [generatedCaption, setGeneratedCaption] = useState(
    t.preview.default_caption
  );

  useEffect(() => {
    if (
      generatedCaption ===
        "여기에 AI가 작성한 최종 캡션과 해시태그가 표시됩니다." ||
      generatedCaption ===
        "The final caption and hashtags generated by AI will be displayed here."
    ) {
      setGeneratedCaption(t.preview.default_caption);
    }
  }, [t, generatedCaption]);

  // 🚨 [추가] 텍스트 양이 많아지면 텍스트창 비율을 자동으로 조금씩 늘려주는 효과
  useEffect(() => {
    const el = rightTextareaRef.current;
    if (!el) return;
    // 내용이 박스보다 길어지면 비율을 최대 66.6%까지 확장
    if (el.scrollHeight > el.clientHeight && textRatio < 66.6) {
      setTextRatio(prev => Math.min(66.6, prev + 2));
    }
  }, [generatedCaption, textRatio]);

  useEffect(() => {
    const fetchPhotos = async () => {
      try {
        const response = await apiClient.get(`/photos/all/${shopId}`);
        setAllPhotos(response.data.photos || []);
      } catch (error) {
        console.error('사진 로딩 실패:', error);
      }
    };

    fetchPhotos();
  }, [shopId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const handleTextareaChange = (
    e: React.ChangeEvent<HTMLTextAreaElement>
  ) => {
    const target = e.target;
    setInputText(target.value);

    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${target.scrollHeight}px`;
    }
  };

  // 🚨 [추가] 우측 텍스트 에디터에서 마우스 휠 이벤트 처리
  const handleRightWheel = (e: React.WheelEvent<HTMLTextAreaElement>) => {
    const el = e.currentTarget;
    const { scrollTop, scrollHeight, clientHeight } = el;
    
    const isAtTop = scrollTop === 0;
    const isAtBottom = Math.abs(scrollHeight - clientHeight - scrollTop) <= 1;

    // 스크롤 올림(위로) & 텍스트 최상단: 이미지 확대 (텍스트 비율 감소)
    if (e.deltaY < 0 && isAtTop) {
      setTextRatio(prev => Math.max(33.3, prev - 4));
    } 
    // 스크롤 내림(아래로) & 텍스트 최하단: 텍스트 확대 (이미지 비율 감소)
    else if (e.deltaY > 0 && isAtBottom) {
      setTextRatio(prev => Math.min(66.6, prev + 4));
    }
  };

  const openPhotoModal = () => {
    setTempSelectedPhotos(images);
    setIsEditModalVisible(true);
  };

  const closePhotoModal = () => {
    setIsEditModalVisible(false);
  };

  const openOrderModal = () => {
    setTempSelectedPhotos(images);
    setIsOrderModalVisible(true);
  };

  const closeOrderModal = () => {
    setIsOrderModalVisible(false);
  };

  const toggleTempSelect = (photo: any) => {
    setTempSelectedPhotos((prev) =>
      prev.some((p) => p.id === photo.id)
        ? prev.filter((p) => p.id !== photo.id)
        : [...prev, photo]
    );
  };

  const handleSavePhotos = () => {
    setImages(tempSelectedPhotos);
    setCurrentImageIndex(0);
    setIsEditModalVisible(false);
  };

  const handleSavePhotoOrder = () => {
    setImages(tempSelectedPhotos);
    setIsOrderModalVisible(false);
  };

  const movePhotoUp = (index: number) => {
    if (index === 0) return;

    const newOrder = [...tempSelectedPhotos];
    [newOrder[index - 1], newOrder[index]] = [
      newOrder[index],
      newOrder[index - 1],
    ];
    setTempSelectedPhotos(newOrder);
  };

  const movePhotoDown = (index: number) => {
    if (index === tempSelectedPhotos.length - 1) return;

    const newOrder = [...tempSelectedPhotos];
    [newOrder[index + 1], newOrder[index]] = [
      newOrder[index],
      newOrder[index + 1],
    ];
    setTempSelectedPhotos(newOrder);
  };

  const handlePrevImage = () => {
    setCurrentImageIndex((prev) => Math.max(0, prev - 1));
  };

  const handleNextImage = () => {
    setCurrentImageIndex((prev) => Math.min(images.length - 1, prev + 1));
  };

  const handleUpload = async () => {
    if (images.length === 0) {
      alert(t.preview.alert_no_photo);
      return;
    }

    if (
      !generatedCaption.trim() ||
      generatedCaption === t.preview.default_caption
    ) {
      alert(t.preview.alert_no_caption);
      return;
    }

    setIsLoading(true);

    try {
      const payload = {
        shop_id: shopId,
        post_id: postId,
        caption: generatedCaption,
        hashtags: [],
        photo_ids: images.map((img) => img.id),
        cta: '',
      };

      const response = await apiClient.post('/save', payload);

      if (response.data.status === 'success') {
        alert(t.preview.alert_save_success);
      }
    } catch (error: any) {
      console.error('업로드 실패:', error);
      alert(error.response?.data?.detail || t.preview.alert_save_error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSendMessage = async (e?: FormEvent) => {
    e?.preventDefault();

    if (!inputText.trim() || isLoading) return;

    const userText = inputText;
    const newMessage: ChatMessage = {
      id: Date.now().toString(),
      sender: 'user',
      text: userText,
    };

    setMessages((prev) => [...prev, newMessage]);
    setInputText('');
    setIsLoading(true);

    const aiMessageId = (Date.now() + 1).toString();
    setMessages((prev) => [
      ...prev,
      { id: aiMessageId, sender: 'ai', text: '' },
    ]);

    try {
      const response = await fetch(
        'https://bybaek-backend-awehcre3f3fpb4fg.koreacentral-01.azurewebsites.net/api/agent/manual_chat',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            shop_id: shopId,
            message: userText,
            photo_ids: images.map((img) => img.id),
          }),
        }
      );

      const reader = response.body?.getReader();
      const decoder = new TextDecoder('utf-8');
      let fullResponse = '';

      while (reader) {
        const { value, done } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        fullResponse += chunk;

        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === aiMessageId ? { ...msg, text: fullResponse } : msg
          )
        );
      }

      setGeneratedCaption(fullResponse);
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleInputKeyDown = (
    e: React.KeyboardEvent<HTMLTextAreaElement>
  ) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="flex flex-row h-screen w-full bg-background overflow-hidden relative">
      <Sidebar />

      {/* 중앙 채팅 영역 */}
      <div className="flex-[1.5] bg-background border-r border-border p-large flex flex-col min-w-0 h-full">
        <div className="mb-large pb-small border-b border-border shrink-0">
          <h1 className="text-h1 text-text-primary font-bold">
            {t.preview.title_chat}
          </h1>
        </div>

        <div className="flex-1 overflow-y-auto flex flex-col gap-4 pr-2 scrollbar-hide min-h-0">
          {messages.map((item) => (
            <div
              key={item.id}
              className={`max-w-[80%] p-medium rounded-xl break-words shrink-0 ${
                item.sender === 'user'
                  ? 'self-end bg-sidebar text-text-inverse'
                  : 'self-start bg-[#F5F5F5] text-text-primary'
              }`}
            >
              <p className="text-body whitespace-pre-wrap">{item.text}</p>
            </div>
          ))}

          {isLoading && (
            <div className="max-w-[80%] p-medium rounded-xl self-start bg-[#F5F5F5] text-text-secondary flex items-center gap-3">
              <div className="w-4 h-4 border-2 border-accent border-t-transparent rounded-full animate-spin" />
              <p className="text-body">{t.preview.ai_typing}</p>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        <form
          onSubmit={handleSendMessage}
          className="flex flex-col py-medium bg-background mt-4 shrink-0"
        >
          <div className="flex items-end gap-2 border border-[#E0E0E0] rounded-lg p-2 bg-background focus-within:border-accent">
            <textarea
              ref={textareaRef}
              rows={1}
              disabled={isLoading}
              className="flex-1 bg-transparent resize-none focus:outline-none min-h-[40px] max-h-[33vh] py-2 px-2"
              placeholder={t.preview.placeholder_req}
              value={inputText}
              onChange={handleTextareaChange}
              onKeyDown={handleInputKeyDown}
            />
            <button
              type="submit"
              disabled={isLoading || !inputText.trim()}
              className="font-bold text-accent px-medium mb-1.5 cursor-pointer"
            >
              {t.preview.btn_send}
            </button>
          </div>
        </form>
      </div>

      {/* 우측 프리뷰 영역 */}
      <div className="flex-1 p-large bg-[#FAFAFA] flex flex-col min-w-0 h-full overflow-hidden">
        <div className="flex flex-row justify-between items-center mb-medium shrink-0">
          <h2 className="text-h2 text-text-primary font-bold">
            {t.preview.title_result}
          </h2>
          <button
            onClick={openPhotoModal}
            className="px-3 py-1.5 border border-accent rounded-md bg-background text-[12px] text-text-secondary font-medium hover:bg-gray-50 cursor-pointer"
          >
            {t.preview.btn_add_photo}
          </button>
        </div>

        {/* 🚨 [수정] flex 비율을 상태(textRatio)로 동적으로 조절, 스무스한 애니메이션 추가 */}
        <div 
          className="relative min-h-0 bg-[#EAEAEA] rounded-lg mb-small overflow-hidden flex items-center justify-center transition-all duration-300 ease-out"
          style={{ flex: 100 - textRatio }}
        >
          <button
            onClick={handlePrevImage}
            disabled={currentImageIndex === 0}
            className="absolute left-2 z-10 text-white text-3xl drop-shadow-md disabled:opacity-30 cursor-pointer"
          >
            {'<'}
          </button>

          <div className="w-full h-full">
            {images.length > 0 ? (
              <img
                src={images[currentImageIndex].blob_url}
                alt="preview"
                className="w-full h-full object-contain"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-text-secondary">
                {t.preview.no_photo}
              </div>
            )}
          </div>

          <button
            onClick={handleNextImage}
            disabled={
              currentImageIndex === images.length - 1 || images.length === 0
            }
            className="absolute right-2 z-10 text-white text-3xl drop-shadow-md disabled:opacity-30 cursor-pointer"
          >
            {'>'}
          </button>
        </div>

        <button
          onClick={openOrderModal}
          className="w-full py-2 mb-medium border border-border rounded-lg bg-white text-[13px] text-text-secondary hover:bg-gray-50 transition-colors shrink-0 cursor-pointer"
        >
          {t.preview.btn_reorder_photo}
        </button>

        {/* 🚨 [수정] flex 비율을 상태(textRatio)로 동적으로 조절, 스무스한 애니메이션 추가 */}
        <div 
          className="min-h-0 bg-background border border-border rounded-lg p-medium mb-large flex flex-col transition-all duration-300 ease-out"
          style={{ flex: textRatio }}
        >
          <textarea
            ref={rightTextareaRef}
            onWheel={handleRightWheel} // 🚨 휠 감지 이벤트 부착
            className="flex-1 w-full h-full resize-none text-body bg-transparent focus:outline-none scrollbar-hide"
            value={generatedCaption}
            onChange={(e) => setGeneratedCaption(e.target.value)}
          />
        </div>

        <div className="shrink-0">
          <button
            onClick={handleUpload}
            className="w-full py-3.5 bg-accent rounded-lg text-white font-bold text-[16px] hover:bg-accent-dark transition-all transform hover:scale-[1.01] active:scale-[0.99] shadow-md cursor-pointer"
          >
            {t.preview.btn_upload_insta}
          </button>
        </div>
      </div>

      {/* 1. 사진 선택 모달 */}
      {isEditModalVisible && (
        <div className="fixed inset-0 flex items-center justify-center bg-black/40 z-[9999]">
          <div className="w-[600px] h-[600px] bg-background rounded-xl shadow-lg p-large flex flex-col">
            <div className="flex justify-between items-center mb-large border-b pb-small">
              <h2 className="text-h2 font-bold">
                {t.preview.modal_photo_select}
              </h2>
              <div className="flex gap-3">
                <button
                  onClick={handleSavePhotos}
                  className="px-5 py-2 bg-accent text-white rounded-md font-bold text-sm cursor-pointer"
                >
                  {t.common.save}
                </button>
                <button
                  onClick={closePhotoModal}
                  className="text-[20px] text-text-secondary cursor-pointer"
                >
                  ✕
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto grid grid-cols-3 gap-4">
              {allPhotos.map((photo) => {
                const isSelected = tempSelectedPhotos.some(
                  (p) => p.id === photo.id
                );

                return (
                  <button
                    key={photo.id}
                    onClick={() => toggleTempSelect(photo)}
                    className={`relative aspect-square rounded-lg border overflow-hidden cursor-pointer ${
                      isSelected
                        ? 'border-accent border-[3px]'
                        : 'border-border'
                    }`}
                  >
                    <div
                      className={`absolute top-2 left-2 w-[22px] h-[22px] rounded border-2 flex justify-center items-center ${
                        isSelected
                          ? 'bg-accent border-accent'
                          : 'bg-white border-text-secondary'
                      }`}
                    >
                      {isSelected && (
                        <span className="text-white text-sm font-bold">✓</span>
                      )}
                    </div>
                    <img
                      src={photo.blob_url}
                      alt={photo.original_name || 'photo'}
                      className="w-full h-full object-cover"
                    />
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* 2. 사진 순서 변경 모달 */}
      {isOrderModalVisible && (
        <div className="fixed inset-0 flex items-center justify-center bg-black/40 z-[9999]">
          <div className="w-[450px] max-h-[600px] bg-background rounded-xl shadow-lg p-large flex flex-col">
            <div className="flex justify-between items-center mb-large border-b pb-small">
              <h2 className="text-h2 font-bold text-text-primary">
                {t.preview.modal_photo_reorder}
              </h2>
              <div className="flex gap-3">
                <button
                  onClick={handleSavePhotoOrder}
                  className="px-5 py-2 bg-accent text-white rounded-md font-bold text-sm cursor-pointer"
                >
                  {t.common.save}
                </button>
                <button
                  onClick={closeOrderModal}
                  className="text-[20px] text-text-secondary cursor-pointer"
                >
                  ✕
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto flex flex-col gap-3 pr-2 scrollbar-hide">
              {tempSelectedPhotos.map((photo, index) => (
                <div
                  key={photo.id}
                  className="flex items-center gap-4 p-3 bg-gray-50 rounded-lg border border-border"
                >
                  <span className="font-bold text-accent w-5">
                    {index + 1}
                  </span>
                  <img
                    src={photo.blob_url}
                    alt={photo.original_name || 'photo'}
                    className="w-16 h-16 object-cover rounded-md"
                  />
                  <div className="flex-1 text-sm font-medium truncate">
                    {photo.original_name}
                  </div>
                  <div className="flex flex-col gap-1">
                    <button
                      onClick={() => movePhotoUp(index)}
                      disabled={index === 0}
                      className="p-1 hover:bg-gray-200 rounded disabled:opacity-30 cursor-pointer"
                    >
                      ▲
                    </button>
                    <button
                      onClick={() => movePhotoDown(index)}
                      disabled={index === tempSelectedPhotos.length - 1}
                      className="p-1 hover:bg-gray-200 rounded disabled:opacity-30 cursor-pointer"
                    >
                      ▼
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}